from oarepo_model_builder_drafts_files.datatypes.components.draft_file_profile import DraftFileComponent
from oarepo_model_builder_drafts_files.datatypes.components.drafts_files_files import InvenioDraftsFilesComponent
from oarepo_model_builder_drafts_files.datatypes.components.drafts_files_field import DraftFilesFieldModelComponent
from oarepo_model_builder_drafts_files.datatypes.components.drafts_files_record import InvenioDraftsFilesRecordComponent

DRAFTS_FILES_COMPONENTS = [InvenioDraftsFilesComponent,  DraftFilesFieldModelComponent, DraftFileComponent, InvenioDraftsFilesRecordComponent]